"""Step 6: BERTopic topic modeling combining UMAP, HDBSCAN, and c-TF-IDF labeling."""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from typing import Optional

import numpy as np
from bertopic import BERTopic
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP

from pipeline_step import PipelineStep
from step_5_embedding_generator import EmbeddingOutput

_DOMAIN_STOP_WORDS = [
    "súmula", "sumula", "stj", "superior", "tribunal", "justiça",
    "federal", "enunciado", "julgador", "relator", "orgão",
    "acórdão", "processo", "número", "ministro", "ministra",
]

_HEADER_RE = re.compile(
    r"DIREITO\s+([\wÁÀÂÃÉÊÍÓÔÕÚÜÇ]+(?:\s+[\wÁÀÂÃÉÊÍÓÔÕÚÜÇ]+)?)\s+-\s+([\wÁÀÂÃÉÊÍÓÔÕÚÜÇ\s]+?)(?=\n|Enunciado|$)",
    re.IGNORECASE,
)


def _extract_header(text: str) -> tuple[str, str] | tuple[None, None]:
    """
    Extract branch and subject from a DIREITO RAMO - SUBJECT header.

    Args:
        text: Raw document text potentially containing the header line

    Returns:
        Tuple of (branch, subject) strings in Title case, or (None, None) if not found
    """
    match = _HEADER_RE.search(text)
    if not match:
        return None, None
    branch = match.group(1).strip().title()
    subject = match.group(2).strip().title()
    return branch, subject


@dataclass
class TopicedSentence:
    """
    A sentence with its BERTopic topic assignment and 2D UMAP coordinates.

    Attributes:
        text: Original sentence text
        topic_id: BERTopic topic assignment (-1 = noise/outlier)
        probability: BERTopic topic membership probability
        reduced_vector: 2D UMAP coordinate for visualization
        embedding: Original 768-dim BERTimbau embedding
    """

    text: str
    topic_id: int
    probability: float
    reduced_vector: np.ndarray
    embedding: np.ndarray


@dataclass
class BerTopicOutput:
    """
    Output of the BERTopic step.

    Attributes:
        topiced_sentences: All sentences with topic assignments
        topic_labels: Dict mapping topic_id to three-level label Branch > Subject > subtype
        topic_branch: Dict mapping topic_id to dominant branch string
        topic_subject: Dict mapping topic_id to dominant subject string
        total_topics: Number of non-noise topics found
        noise_count: Number of outlier sentences (topic_id == -1)
        source_path: Propagated from previous step
    """

    topiced_sentences: list[TopicedSentence]
    topic_labels: dict[int, str]
    topic_branch: dict[int, str]
    topic_subject: dict[int, str]
    total_topics: int
    noise_count: int
    source_path: Optional[object] = None


class BerTopicStep(PipelineStep):
    """
    Apply BERTopic using embedding similarity for free clustering.

    Extracts branch and subject from each document's DIREITO RAMO - SUBJECT header
    via majority vote post-clustering. Produces three-level labels:
    Branch > Subject > c-TF-IDF subtype, with subtype words deduplicated against
    branch and subject.
    """

    def __init__(
        self,
        n_neighbors: int = 15,
        min_cluster_size: int = 2,
        top_n_words: int = 5,
        random_state: int = 42,
    ):
        """
        Initialize BERTopic step with configurable sub-model parameters.

        Args:
            n_neighbors: UMAP neighborhood size for local manifold approximation
            min_cluster_size: HDBSCAN minimum cluster size; minimum valid value is 2
            top_n_words: Number of keywords per topic label generated by c-TF-IDF
            random_state: Seed for UMAP reproducibility
        """
        super().__init__(
            step_number=6,
            name="BERTopic",
            description="Free-clustering topic modeling with UMAP + HDBSCAN + c-TF-IDF",
        )
        umap_model = UMAP(
            n_components=2,
            n_neighbors=n_neighbors,
            min_dist=0.0,
            metric="cosine",
            random_state=random_state,
        )
        hdbscan_model = HDBSCAN(
            min_cluster_size=min_cluster_size,
            min_samples=1,
            metric="euclidean",
            prediction_data=True,
        )
        vectorizer_model = CountVectorizer(
            token_pattern=r"(?u)\b[a-záàâãéêíóôõúüç]{4,}\b",
            stop_words=_DOMAIN_STOP_WORDS,
            ngram_range=(1, 2),
        )
        self._topic_model = BERTopic(
            umap_model=umap_model,
            hdbscan_model=hdbscan_model,
            vectorizer_model=vectorizer_model,
            representation_model=None,
            top_n_words=top_n_words,
            verbose=False,
            calculate_probabilities=True,
            language="multilingual",
        )

    def process(self, input_data: EmbeddingOutput) -> BerTopicOutput:
        """
        Fit BERTopic on pre-computed embeddings using free embedding-similarity clustering.

        Args:
            input_data: EmbeddingOutput with 768-dim BERTimbau embeddings per sentence

        Returns:
            BerTopicOutput with three-level topic labels, branch/subject dicts, and 2D coordinates
        """
        docs = [s.text for s in input_data.embedded_sentences]
        embeddings = np.stack([s.embedding for s in input_data.embedded_sentences])
        headers = [_extract_header(doc) for doc in docs]
        topics, probs = self._topic_model.fit_transform(docs, embeddings=embeddings)
        reduced = self._topic_model.umap_model.embedding_
        topic_labels, topic_branch, topic_subject = self._build_topic_labels(docs, topics, headers)
        topiced_sentences = [
            TopicedSentence(
                text=doc,
                topic_id=int(topic_id),
                probability=float(np.max(prob)) if hasattr(prob, "__len__") else float(prob),
                reduced_vector=reduced[idx],
                embedding=input_data.embedded_sentences[idx].embedding,
            )
            for idx, (doc, topic_id, prob) in enumerate(zip(docs, topics, probs))
        ]
        unique_topics = {s.topic_id for s in topiced_sentences if s.topic_id != -1}
        noise_count = sum(1 for s in topiced_sentences if s.topic_id == -1)
        return BerTopicOutput(
            topiced_sentences=topiced_sentences,
            topic_labels=topic_labels,
            topic_branch=topic_branch,
            topic_subject=topic_subject,
            total_topics=len(unique_topics),
            noise_count=noise_count,
            source_path=input_data.source_path,
        )

    def _filter_subtype_keywords(
        self,
        keywords: list,
        branch: str,
        subject: str,
    ) -> list[str]:
        """
        Remove keywords that overlap with branch or subject label words.

        Args:
            keywords: c-TF-IDF keyword list, each item is a string or (word, score) tuple
            branch: Dominant branch label for this topic
            subject: Dominant subject label for this topic

        Returns:
            Filtered keyword list with no words already present in branch or subject
        """
        existing: set[str] = set()
        for part in [branch, subject]:
            for word in re.split(r"[\s_]+", part.lower()):
                if len(word) >= 3:
                    existing.add(word)
        result = []
        for kw in keywords:
            word = (kw[0] if isinstance(kw, tuple) else kw).lower()
            if not any(word == e or e in word or word in e for e in existing):
                result.append(kw)
        return result

    def _build_topic_labels(
        self,
        docs: list[str],
        topics: list[int],
        headers: list[tuple],
    ) -> tuple[dict[int, str], dict[int, str], dict[int, str]]:
        """
        Build three-level labels combining branch, subject, and c-TF-IDF subtype.

        Args:
            docs: Raw document texts corresponding to each topic assignment
            topics: Integer topic IDs assigned by BERTopic per document
            headers: List of (branch, subject) tuples extracted from each document

        Returns:
            Tuple of (topic_labels, topic_branch, topic_subject) dicts keyed by topic_id
        """
        branch_by_topic: dict[int, list[str]] = {}
        subject_by_topic: dict[int, list[str]] = {}
        for _, topic_id, (branch, subject) in zip(docs, topics, headers):
            if topic_id == -1:
                continue
            if branch:
                branch_by_topic.setdefault(topic_id, []).append(branch)
            if subject:
                subject_by_topic.setdefault(topic_id, []).append(subject)
        topic_info = self._topic_model.get_topic_info()
        ctfidf_subtypes: dict[int, str] = {}
        for _, row in topic_info.iterrows():
            tid = int(row["Topic"])
            if tid == -1:
                continue
            keywords = row["Representation"]
            branch_str = Counter(branch_by_topic.get(tid, [])).most_common(1)
            subject_str = Counter(subject_by_topic.get(tid, [])).most_common(1)
            branch_label = branch_str[0][0] if branch_str else ""
            subject_label = subject_str[0][0] if subject_str else ""
            filtered = self._filter_subtype_keywords(keywords, branch_label, subject_label)
            subtype = "_".join(
                (kw[0] if isinstance(kw, tuple) else kw)
                for kw in filtered[:3]
            )
            ctfidf_subtypes[tid] = subtype
        all_topic_ids = {t for t in topics if t != -1}
        labels: dict[int, str] = {}
        branches: dict[int, str] = {}
        subjects: dict[int, str] = {}
        for tid in all_topic_ids:
            branch = Counter(branch_by_topic.get(tid, [])).most_common(1)
            subject = Counter(subject_by_topic.get(tid, [])).most_common(1)
            subtype = ctfidf_subtypes.get(tid, "")
            branch_str = branch[0][0] if branch else "Desconhecido"
            subject_str = subject[0][0] if subject else "Desconhecido"
            branches[tid] = branch_str
            subjects[tid] = subject_str
            labels[tid] = f"{branch_str} > {subject_str} > {subtype}" if subtype else f"{branch_str} > {subject_str}"
        return labels, branches, subjects

    def validate(self, output_data: BerTopicOutput) -> bool:
        """
        Validate that BERTopic processing completed with a non-negative topic count.

        Args:
            output_data: BerTopicOutput to validate

        Returns:
            True if total_topics is non-negative
        """
        return output_data.total_topics >= 0
