"""Step 6: BERTopic topic modeling combining UMAP, HDBSCAN, and c-TF-IDF labeling."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer
from umap import UMAP

from pipeline_step import PipelineStep
from step_5_embedding_generator import EmbeddingOutput


@dataclass
class TopicedSentence:
    """
    A sentence with its BERTopic topic assignment and 2D UMAP coordinates.

    Attributes:
        text: Original sentence text
        topic_id: BERTopic topic assignment (-1 = noise/outlier)
        probability: BERTopic topic membership probability
        reduced_vector: 2D UMAP coordinate for visualization
        embedding: Original 768-dim BERTimbau embedding
    """

    text: str
    topic_id: int
    probability: float
    reduced_vector: np.ndarray
    embedding: np.ndarray


@dataclass
class BerTopicOutput:
    """
    Output of the BERTopic step.

    Attributes:
        topiced_sentences: All sentences with topic assignments
        topic_labels: Dict mapping topic_id to auto-generated keyword label
        total_topics: Number of non-noise topics found
        noise_count: Number of outlier sentences (topic_id == -1)
        source_path: Propagated from previous step
    """

    topiced_sentences: list[TopicedSentence]
    topic_labels: dict[int, str]
    total_topics: int
    noise_count: int
    source_path: Optional[object] = None


class BerTopicStep(PipelineStep):
    """
    Apply BERTopic to embed sentences into topics using UMAP + HDBSCAN + c-TF-IDF.

    BERTopic internally runs UMAP to reduce dimensionality, HDBSCAN to cluster
    sentences, and c-TF-IDF to auto-generate keyword labels per topic. This
    replaces the separate Steps 6, 7, and 8 from the previous pipeline design.
    Pre-computed BERTimbau embeddings are passed directly to avoid re-embedding.
    """

    def __init__(
        self,
        n_neighbors: int = 15,
        min_cluster_size: int = 5,
        top_n_words: int = 5,
        random_state: int = 42,
        sentence_model_name: str = "neuralmind/bert-base-portuguese-cased",
    ):
        """
        Initialize BERTopic step with configurable sub-model parameters.

        Args:
            n_neighbors: UMAP neighborhood size for local manifold approximation
            min_cluster_size: HDBSCAN minimum cluster size for density estimation
            top_n_words: Number of keywords per topic label generated by c-TF-IDF
            random_state: Seed for UMAP reproducibility
            sentence_model_name: HuggingFace model name for KeyBERTInspired representation
        """
        super().__init__(
            step_number=6,
            name="BERTopic",
            description="Topic modeling with UMAP + HDBSCAN + c-TF-IDF auto-labeling",
        )
        umap_model = UMAP(
            n_components=2,
            n_neighbors=n_neighbors,
            min_dist=0.0,
            metric="cosine",
            random_state=random_state,
        )
        hdbscan_model = HDBSCAN(
            min_cluster_size=min_cluster_size,
            metric="euclidean",
            prediction_data=True,
        )
        sentence_model = SentenceTransformer(sentence_model_name)
        representation_model = KeyBERTInspired()
        self._topic_model = BERTopic(
            embedding_model=sentence_model,
            umap_model=umap_model,
            hdbscan_model=hdbscan_model,
            representation_model=representation_model,
            top_n_words=top_n_words,
            verbose=False,
            calculate_probabilities=True,
            language="multilingual",
        )

    def process(self, input_data: EmbeddingOutput) -> BerTopicOutput:
        """
        Fit BERTopic on pre-computed embeddings and extract topic assignments.

        Args:
            input_data: EmbeddingOutput with 768-dim BERTimbau embeddings per sentence

        Returns:
            BerTopicOutput with topic assignments, keyword labels, and 2D coordinates
        """
        docs = [s.text for s in input_data.embedded_sentences]
        embeddings = np.stack([s.embedding for s in input_data.embedded_sentences])
        topics, probs = self._topic_model.fit_transform(docs, embeddings=embeddings)
        reduced = self._topic_model.umap_model.embedding_
        topic_labels = self._build_topic_labels()
        prob_list = list(probs) if not isinstance(probs, list) else probs
        topiced_sentences = [
            TopicedSentence(
                text=doc,
                topic_id=int(topic_id),
                probability=float(np.max(prob)) if isinstance(prob, np.ndarray) else float(prob),
                reduced_vector=reduced[idx],
                embedding=input_data.embedded_sentences[idx].embedding,
            )
            for idx, (doc, topic_id, prob) in enumerate(zip(docs, topics, prob_list))
        ]
        unique_topics = {s.topic_id for s in topiced_sentences if s.topic_id != -1}
        noise_count = sum(1 for s in topiced_sentences if s.topic_id == -1)
        return BerTopicOutput(
            topiced_sentences=topiced_sentences,
            topic_labels=topic_labels,
            total_topics=len(unique_topics),
            noise_count=noise_count,
            source_path=input_data.source_path,
        )

    def _build_topic_labels(self) -> dict[int, str]:
        """
        Extract keyword labels for each non-noise topic from BERTopic topic info.

        Returns:
            Dict mapping topic_id to underscore-joined top-3 keyword label string
        """
        topic_info = self._topic_model.get_topic_info()
        labels: dict[int, str] = {}
        for _, row in topic_info.iterrows():
            topic_id = int(row["Topic"])
            if topic_id == -1:
                continue
            keywords: list = row["Representation"]
            label = "_".join(kw[0] if isinstance(kw, tuple) else kw for kw in keywords[:3])
            labels[topic_id] = label
        return labels

    def validate(self, output_data: BerTopicOutput) -> bool:
        """
        Validate that BERTopic processing completed with a non-negative topic count.

        Args:
            output_data: BerTopicOutput to validate

        Returns:
            True if total_topics is non-negative
        """
        return output_data.total_topics >= 0
